### API error 404
GET http://localhost:3000/sqdqsd


### ADDING A USER
POST http://localhost:3000/signup
Content-Type: application/json

{
    "email": "testingadd@biblio.io",
    "password": "testingadd",
    "passwordConfirm": "testingadd",
    "firstname": "testingadd",
    "lastname": "testingadd"
}

### try login 
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "testingadd@biblio.io",
    "password": "testingadd"
}


### try login wrong password 
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "testingadd@biblio.io",
    "password": "test"
}

